// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/CustomerVo.proto

package net.rod.demo.customer.vo;

public final class CustomerVoOuterClass {
  private CustomerVoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CustomerVoListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:customer.CustomerVoList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .customer.CustomerVo customerVos = 1;</code>
     */
    java.util.List<CustomerVoOuterClass.CustomerVo>
        getCustomerVosList();
    /**
     * <code>repeated .customer.CustomerVo customerVos = 1;</code>
     */
    CustomerVoOuterClass.CustomerVo getCustomerVos(int index);
    /**
     * <code>repeated .customer.CustomerVo customerVos = 1;</code>
     */
    int getCustomerVosCount();
    /**
     * <code>repeated .customer.CustomerVo customerVos = 1;</code>
     */
    java.util.List<? extends CustomerVoOuterClass.CustomerVoOrBuilder>
        getCustomerVosOrBuilderList();
    /**
     * <code>repeated .customer.CustomerVo customerVos = 1;</code>
     */
    CustomerVoOuterClass.CustomerVoOrBuilder getCustomerVosOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code customer.CustomerVoList}
   */
  public static final class CustomerVoList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:customer.CustomerVoList)
      CustomerVoListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CustomerVoList.newBuilder() to construct.
    private CustomerVoList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CustomerVoList() {
      customerVos_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CustomerVoList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CustomerVoList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                customerVos_ = new java.util.ArrayList<CustomerVoOuterClass.CustomerVo>();
                mutable_bitField0_ |= 0x00000001;
              }
              customerVos_.add(
                  input.readMessage(CustomerVoOuterClass.CustomerVo.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          customerVos_ = java.util.Collections.unmodifiableList(customerVos_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CustomerVoOuterClass.internal_static_customer_CustomerVoList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CustomerVoOuterClass.internal_static_customer_CustomerVoList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CustomerVoOuterClass.CustomerVoList.class, CustomerVoOuterClass.CustomerVoList.Builder.class);
    }

    public static final int CUSTOMERVOS_FIELD_NUMBER = 1;
    private java.util.List<CustomerVoOuterClass.CustomerVo> customerVos_;
    /**
     * <code>repeated .customer.CustomerVo customerVos = 1;</code>
     */
    @java.lang.Override
    public java.util.List<CustomerVoOuterClass.CustomerVo> getCustomerVosList() {
      return customerVos_;
    }
    /**
     * <code>repeated .customer.CustomerVo customerVos = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends CustomerVoOuterClass.CustomerVoOrBuilder>
        getCustomerVosOrBuilderList() {
      return customerVos_;
    }
    /**
     * <code>repeated .customer.CustomerVo customerVos = 1;</code>
     */
    @java.lang.Override
    public int getCustomerVosCount() {
      return customerVos_.size();
    }
    /**
     * <code>repeated .customer.CustomerVo customerVos = 1;</code>
     */
    @java.lang.Override
    public CustomerVoOuterClass.CustomerVo getCustomerVos(int index) {
      return customerVos_.get(index);
    }
    /**
     * <code>repeated .customer.CustomerVo customerVos = 1;</code>
     */
    @java.lang.Override
    public CustomerVoOuterClass.CustomerVoOrBuilder getCustomerVosOrBuilder(
        int index) {
      return customerVos_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < customerVos_.size(); i++) {
        output.writeMessage(1, customerVos_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < customerVos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, customerVos_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CustomerVoOuterClass.CustomerVoList)) {
        return super.equals(obj);
      }
      CustomerVoOuterClass.CustomerVoList other = (CustomerVoOuterClass.CustomerVoList) obj;

      if (!getCustomerVosList()
          .equals(other.getCustomerVosList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCustomerVosCount() > 0) {
        hash = (37 * hash) + CUSTOMERVOS_FIELD_NUMBER;
        hash = (53 * hash) + getCustomerVosList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CustomerVoOuterClass.CustomerVoList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CustomerVoOuterClass.CustomerVoList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CustomerVoOuterClass.CustomerVoList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CustomerVoOuterClass.CustomerVoList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CustomerVoOuterClass.CustomerVoList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CustomerVoOuterClass.CustomerVoList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CustomerVoOuterClass.CustomerVoList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CustomerVoOuterClass.CustomerVoList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CustomerVoOuterClass.CustomerVoList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CustomerVoOuterClass.CustomerVoList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CustomerVoOuterClass.CustomerVoList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CustomerVoOuterClass.CustomerVoList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CustomerVoOuterClass.CustomerVoList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code customer.CustomerVoList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:customer.CustomerVoList)
        CustomerVoOuterClass.CustomerVoListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CustomerVoOuterClass.internal_static_customer_CustomerVoList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CustomerVoOuterClass.internal_static_customer_CustomerVoList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CustomerVoOuterClass.CustomerVoList.class, CustomerVoOuterClass.CustomerVoList.Builder.class);
      }

      // Construct using net.rod.demo.customer.vo.CustomerVoOuterClass.CustomerVoList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCustomerVosFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (customerVosBuilder_ == null) {
          customerVos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          customerVosBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CustomerVoOuterClass.internal_static_customer_CustomerVoList_descriptor;
      }

      @java.lang.Override
      public CustomerVoOuterClass.CustomerVoList getDefaultInstanceForType() {
        return CustomerVoOuterClass.CustomerVoList.getDefaultInstance();
      }

      @java.lang.Override
      public CustomerVoOuterClass.CustomerVoList build() {
        CustomerVoOuterClass.CustomerVoList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public CustomerVoOuterClass.CustomerVoList buildPartial() {
        CustomerVoOuterClass.CustomerVoList result = new CustomerVoOuterClass.CustomerVoList(this);
        int from_bitField0_ = bitField0_;
        if (customerVosBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            customerVos_ = java.util.Collections.unmodifiableList(customerVos_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.customerVos_ = customerVos_;
        } else {
          result.customerVos_ = customerVosBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CustomerVoOuterClass.CustomerVoList) {
          return mergeFrom((CustomerVoOuterClass.CustomerVoList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CustomerVoOuterClass.CustomerVoList other) {
        if (other == CustomerVoOuterClass.CustomerVoList.getDefaultInstance()) return this;
        if (customerVosBuilder_ == null) {
          if (!other.customerVos_.isEmpty()) {
            if (customerVos_.isEmpty()) {
              customerVos_ = other.customerVos_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCustomerVosIsMutable();
              customerVos_.addAll(other.customerVos_);
            }
            onChanged();
          }
        } else {
          if (!other.customerVos_.isEmpty()) {
            if (customerVosBuilder_.isEmpty()) {
              customerVosBuilder_.dispose();
              customerVosBuilder_ = null;
              customerVos_ = other.customerVos_;
              bitField0_ = (bitField0_ & ~0x00000001);
              customerVosBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCustomerVosFieldBuilder() : null;
            } else {
              customerVosBuilder_.addAllMessages(other.customerVos_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CustomerVoOuterClass.CustomerVoList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CustomerVoOuterClass.CustomerVoList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<CustomerVoOuterClass.CustomerVo> customerVos_ =
        java.util.Collections.emptyList();
      private void ensureCustomerVosIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          customerVos_ = new java.util.ArrayList<CustomerVoOuterClass.CustomerVo>(customerVos_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          CustomerVoOuterClass.CustomerVo, CustomerVoOuterClass.CustomerVo.Builder, CustomerVoOuterClass.CustomerVoOrBuilder> customerVosBuilder_;

      /**
       * <code>repeated .customer.CustomerVo customerVos = 1;</code>
       */
      public java.util.List<CustomerVoOuterClass.CustomerVo> getCustomerVosList() {
        if (customerVosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(customerVos_);
        } else {
          return customerVosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .customer.CustomerVo customerVos = 1;</code>
       */
      public int getCustomerVosCount() {
        if (customerVosBuilder_ == null) {
          return customerVos_.size();
        } else {
          return customerVosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .customer.CustomerVo customerVos = 1;</code>
       */
      public CustomerVoOuterClass.CustomerVo getCustomerVos(int index) {
        if (customerVosBuilder_ == null) {
          return customerVos_.get(index);
        } else {
          return customerVosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .customer.CustomerVo customerVos = 1;</code>
       */
      public Builder setCustomerVos(
          int index, CustomerVoOuterClass.CustomerVo value) {
        if (customerVosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomerVosIsMutable();
          customerVos_.set(index, value);
          onChanged();
        } else {
          customerVosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .customer.CustomerVo customerVos = 1;</code>
       */
      public Builder setCustomerVos(
          int index, CustomerVoOuterClass.CustomerVo.Builder builderForValue) {
        if (customerVosBuilder_ == null) {
          ensureCustomerVosIsMutable();
          customerVos_.set(index, builderForValue.build());
          onChanged();
        } else {
          customerVosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .customer.CustomerVo customerVos = 1;</code>
       */
      public Builder addCustomerVos(CustomerVoOuterClass.CustomerVo value) {
        if (customerVosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomerVosIsMutable();
          customerVos_.add(value);
          onChanged();
        } else {
          customerVosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .customer.CustomerVo customerVos = 1;</code>
       */
      public Builder addCustomerVos(
          int index, CustomerVoOuterClass.CustomerVo value) {
        if (customerVosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomerVosIsMutable();
          customerVos_.add(index, value);
          onChanged();
        } else {
          customerVosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .customer.CustomerVo customerVos = 1;</code>
       */
      public Builder addCustomerVos(
          CustomerVoOuterClass.CustomerVo.Builder builderForValue) {
        if (customerVosBuilder_ == null) {
          ensureCustomerVosIsMutable();
          customerVos_.add(builderForValue.build());
          onChanged();
        } else {
          customerVosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .customer.CustomerVo customerVos = 1;</code>
       */
      public Builder addCustomerVos(
          int index, CustomerVoOuterClass.CustomerVo.Builder builderForValue) {
        if (customerVosBuilder_ == null) {
          ensureCustomerVosIsMutable();
          customerVos_.add(index, builderForValue.build());
          onChanged();
        } else {
          customerVosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .customer.CustomerVo customerVos = 1;</code>
       */
      public Builder addAllCustomerVos(
          java.lang.Iterable<? extends CustomerVoOuterClass.CustomerVo> values) {
        if (customerVosBuilder_ == null) {
          ensureCustomerVosIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, customerVos_);
          onChanged();
        } else {
          customerVosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .customer.CustomerVo customerVos = 1;</code>
       */
      public Builder clearCustomerVos() {
        if (customerVosBuilder_ == null) {
          customerVos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          customerVosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .customer.CustomerVo customerVos = 1;</code>
       */
      public Builder removeCustomerVos(int index) {
        if (customerVosBuilder_ == null) {
          ensureCustomerVosIsMutable();
          customerVos_.remove(index);
          onChanged();
        } else {
          customerVosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .customer.CustomerVo customerVos = 1;</code>
       */
      public CustomerVoOuterClass.CustomerVo.Builder getCustomerVosBuilder(
          int index) {
        return getCustomerVosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .customer.CustomerVo customerVos = 1;</code>
       */
      public CustomerVoOuterClass.CustomerVoOrBuilder getCustomerVosOrBuilder(
          int index) {
        if (customerVosBuilder_ == null) {
          return customerVos_.get(index);  } else {
          return customerVosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .customer.CustomerVo customerVos = 1;</code>
       */
      public java.util.List<? extends CustomerVoOuterClass.CustomerVoOrBuilder>
           getCustomerVosOrBuilderList() {
        if (customerVosBuilder_ != null) {
          return customerVosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(customerVos_);
        }
      }
      /**
       * <code>repeated .customer.CustomerVo customerVos = 1;</code>
       */
      public CustomerVoOuterClass.CustomerVo.Builder addCustomerVosBuilder() {
        return getCustomerVosFieldBuilder().addBuilder(
            CustomerVoOuterClass.CustomerVo.getDefaultInstance());
      }
      /**
       * <code>repeated .customer.CustomerVo customerVos = 1;</code>
       */
      public CustomerVoOuterClass.CustomerVo.Builder addCustomerVosBuilder(
          int index) {
        return getCustomerVosFieldBuilder().addBuilder(
            index, CustomerVoOuterClass.CustomerVo.getDefaultInstance());
      }
      /**
       * <code>repeated .customer.CustomerVo customerVos = 1;</code>
       */
      public java.util.List<CustomerVoOuterClass.CustomerVo.Builder>
           getCustomerVosBuilderList() {
        return getCustomerVosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          CustomerVoOuterClass.CustomerVo, CustomerVoOuterClass.CustomerVo.Builder, CustomerVoOuterClass.CustomerVoOrBuilder>
          getCustomerVosFieldBuilder() {
        if (customerVosBuilder_ == null) {
          customerVosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              CustomerVoOuterClass.CustomerVo, CustomerVoOuterClass.CustomerVo.Builder, CustomerVoOuterClass.CustomerVoOrBuilder>(
                  customerVos_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          customerVos_ = null;
        }
        return customerVosBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:customer.CustomerVoList)
    }

    // @@protoc_insertion_point(class_scope:customer.CustomerVoList)
    private static final CustomerVoOuterClass.CustomerVoList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CustomerVoOuterClass.CustomerVoList();
    }

    public static CustomerVoOuterClass.CustomerVoList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CustomerVoList>
        PARSER = new com.google.protobuf.AbstractParser<CustomerVoList>() {
      @java.lang.Override
      public CustomerVoList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CustomerVoList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CustomerVoList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CustomerVoList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public CustomerVoOuterClass.CustomerVoList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CustomerVoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:customer.CustomerVo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string address = 3;</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <code>string address = 3;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>string email = 4;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 4;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string phone = 5;</code>
     * @return The phone.
     */
    java.lang.String getPhone();
    /**
     * <code>string phone = 5;</code>
     * @return The bytes for phone.
     */
    com.google.protobuf.ByteString
        getPhoneBytes();
  }
  /**
   * Protobuf type {@code customer.CustomerVo}
   */
  public static final class CustomerVo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:customer.CustomerVo)
      CustomerVoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CustomerVo.newBuilder() to construct.
    private CustomerVo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CustomerVo() {
      name_ = "";
      address_ = "";
      email_ = "";
      phone_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CustomerVo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CustomerVo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              phone_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CustomerVoOuterClass.internal_static_customer_CustomerVo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CustomerVoOuterClass.internal_static_customer_CustomerVo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CustomerVoOuterClass.CustomerVo.class, CustomerVoOuterClass.CustomerVo.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 3;
    private volatile java.lang.Object address_;
    /**
     * <code>string address = 3;</code>
     * @return The address.
     */
    @java.lang.Override
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 3;</code>
     * @return The bytes for address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 4;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 4;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONE_FIELD_NUMBER = 5;
    private volatile java.lang.Object phone_;
    /**
     * <code>string phone = 5;</code>
     * @return The phone.
     */
    @java.lang.Override
    public java.lang.String getPhone() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phone_ = s;
        return s;
      }
    }
    /**
     * <code>string phone = 5;</code>
     * @return The bytes for phone.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, address_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, email_);
      }
      if (!getPhoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, phone_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, address_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, email_);
      }
      if (!getPhoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, phone_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CustomerVoOuterClass.CustomerVo)) {
        return super.equals(obj);
      }
      CustomerVoOuterClass.CustomerVo other = (CustomerVoOuterClass.CustomerVo) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!getPhone()
          .equals(other.getPhone())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + PHONE_FIELD_NUMBER;
      hash = (53 * hash) + getPhone().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CustomerVoOuterClass.CustomerVo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CustomerVoOuterClass.CustomerVo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CustomerVoOuterClass.CustomerVo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CustomerVoOuterClass.CustomerVo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CustomerVoOuterClass.CustomerVo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CustomerVoOuterClass.CustomerVo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CustomerVoOuterClass.CustomerVo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CustomerVoOuterClass.CustomerVo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CustomerVoOuterClass.CustomerVo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CustomerVoOuterClass.CustomerVo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CustomerVoOuterClass.CustomerVo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CustomerVoOuterClass.CustomerVo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CustomerVoOuterClass.CustomerVo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code customer.CustomerVo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:customer.CustomerVo)
        CustomerVoOuterClass.CustomerVoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CustomerVoOuterClass.internal_static_customer_CustomerVo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CustomerVoOuterClass.internal_static_customer_CustomerVo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CustomerVoOuterClass.CustomerVo.class, CustomerVoOuterClass.CustomerVo.Builder.class);
      }

      // Construct using net.rod.demo.customer.vo.CustomerVoOuterClass.CustomerVo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        address_ = "";

        email_ = "";

        phone_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CustomerVoOuterClass.internal_static_customer_CustomerVo_descriptor;
      }

      @java.lang.Override
      public CustomerVoOuterClass.CustomerVo getDefaultInstanceForType() {
        return CustomerVoOuterClass.CustomerVo.getDefaultInstance();
      }

      @java.lang.Override
      public CustomerVoOuterClass.CustomerVo build() {
        CustomerVoOuterClass.CustomerVo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public CustomerVoOuterClass.CustomerVo buildPartial() {
        CustomerVoOuterClass.CustomerVo result = new CustomerVoOuterClass.CustomerVo(this);
        result.id_ = id_;
        result.name_ = name_;
        result.address_ = address_;
        result.email_ = email_;
        result.phone_ = phone_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CustomerVoOuterClass.CustomerVo) {
          return mergeFrom((CustomerVoOuterClass.CustomerVo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CustomerVoOuterClass.CustomerVo other) {
        if (other == CustomerVoOuterClass.CustomerVo.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (!other.getPhone().isEmpty()) {
          phone_ = other.phone_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CustomerVoOuterClass.CustomerVo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CustomerVoOuterClass.CustomerVo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>string address = 3;</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address = 3;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 3;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string address = 3;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 4;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object phone_ = "";
      /**
       * <code>string phone = 5;</code>
       * @return The phone.
       */
      public java.lang.String getPhone() {
        java.lang.Object ref = phone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string phone = 5;</code>
       * @return The bytes for phone.
       */
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        java.lang.Object ref = phone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string phone = 5;</code>
       * @param value The phone to set.
       * @return This builder for chaining.
       */
      public Builder setPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string phone = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhone() {
        
        phone_ = getDefaultInstance().getPhone();
        onChanged();
        return this;
      }
      /**
       * <code>string phone = 5;</code>
       * @param value The bytes for phone to set.
       * @return This builder for chaining.
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phone_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:customer.CustomerVo)
    }

    // @@protoc_insertion_point(class_scope:customer.CustomerVo)
    private static final CustomerVoOuterClass.CustomerVo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CustomerVoOuterClass.CustomerVo();
    }

    public static CustomerVoOuterClass.CustomerVo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CustomerVo>
        PARSER = new com.google.protobuf.AbstractParser<CustomerVo>() {
      @java.lang.Override
      public CustomerVo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CustomerVo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CustomerVo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CustomerVo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public CustomerVoOuterClass.CustomerVo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_customer_CustomerVoList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_customer_CustomerVoList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_customer_CustomerVo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_customer_CustomerVo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#src/main/resources/CustomerVo.proto\022\010c" +
      "ustomer\";\n\016CustomerVoList\022)\n\013customerVos" +
      "\030\001 \003(\0132\024.customer.CustomerVo\"U\n\nCustomer" +
      "Vo\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\017\n\007address\030" +
      "\003 \001(\t\022\r\n\005email\030\004 \001(\t\022\r\n\005phone\030\005 \001(\tB\027\n\025n" +
      "et.rod.demo.customerb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_customer_CustomerVoList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_customer_CustomerVoList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_customer_CustomerVoList_descriptor,
        new java.lang.String[] { "CustomerVos", });
    internal_static_customer_CustomerVo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_customer_CustomerVo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_customer_CustomerVo_descriptor,
        new java.lang.String[] { "Id", "Name", "Address", "Email", "Phone", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
