spring:
  datasource:
    url: jdbc:mysql://localhost:3308/ec_product?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: product
    password: report
  jpa:
    show-sql: true
  redis:
    host: localhost
    port: 6379
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
server:
  port: 8083
  servlet:
    context-path: /product
  compression:
    enabled: on
logging:
  level:
     org.springframework.web: ERROR
     net.rod.demo: DEBUG